// Generated by CoffeeScript 1.6.3
(function() {
  var longestWord, numberSearch,
    __indexOf = [].indexOf || function(item) { for (var i = 0, l = this.length; i < l; i++) { if (i in this && this[i] === item) return i; } return -1; };

  numberSearch = function(string) {
    var char, digits, i, letters, num, sumValues, total, _i, _j, _k, _l, _len, _len1, _ref, _ref1, _ref2, _results, _results1;
    digits = [];
    sumValues = [];
    total = 0;
    letters = 0;
    for (i = _i = 0, _len = string.length; _i < _len; i = ++_i) {
      char = string[i];
      if (_ref = string.charCodeAt(i), __indexOf.call([48, 49, 50, 51, 52, 53, 54, 55, 56, 57], _ref) >= 0) {
        digits.push(char);
      } else {
        if ((_ref1 = char.charCodeAt(0), __indexOf.call((function() {
          _results = [];
          for (_j = 65; _j <= 90; _j++){ _results.push(_j); }
          return _results;
        }).apply(this), _ref1) >= 0) || (_ref2 = char.charCodeAt(0), __indexOf.call((function() {
          _results1 = [];
          for (_k = 97; _k <= 122; _k++){ _results1.push(_k); }
          return _results1;
        }).apply(this), _ref2) >= 0)) {
          ++letters;
        }
        sumValues.push(+digits.join(""));
        digits = [];
      }
    }
    for (_l = 0, _len1 = sumValues.length; _l < _len1; _l++) {
      num = sumValues[_l];
      total += num;
    }
    return Math.round(total / letters);
  };

  longestWord = function(string) {
    var largest, lengths, maxIndex, words;
    words = string.split(" ");
    lengths = words.map(function(word) {
      var letter, trimWord, _i, _j, _k, _len, _ref, _ref1, _results, _results1;
      trimWord = word;
      for (_i = 0, _len = word.length; _i < _len; _i++) {
        letter = word[_i];
        if ((_ref = letter.charCodeAt(0), __indexOf.call((function() {
          _results = [];
          for (_j = 65; _j <= 90; _j++){ _results.push(_j); }
          return _results;
        }).apply(this), _ref) < 0) && (_ref1 = letter.charCodeAt(0), __indexOf.call((function() {
          _results1 = [];
          for (_k = 97; _k <= 122; _k++){ _results1.push(_k); }
          return _results1;
        }).apply(this), _ref1) < 0)) {
          trimWord = trimWord.replace(letter, "");
        }
      }
      return trimWord.length;
    });
    largest = Math.max.apply(Math, lengths);
    maxIndex = lengths.indexOf(largest);
    return words[maxIndex];
  };

  console.log(numberSearch("Hello6 9World 2, Nic8e D7ay!"));

}).call(this);
